In [1]:
import numpy as np

In [3]:
a1=np.array([2,3,4,5,6])
a1

array([2, 3, 4, 5, 6])

In [4]:
type(a1)


numpy.ndarray

In [5]:
a1.shape

(5,)

In [11]:
b1=[4.5,5.1,6.2]
b1

[4.5, 5.1, 6.2]

In [13]:
type(b1)

list

In [14]:
c1=[[1,2,3,],
   [5,6,7]]
c1

[[1, 2, 3], [5, 6, 7]]

In [15]:
c1=np.array(c1)

In [16]:
type(c1)

numpy.ndarray

In [17]:
c1.shape

(2, 3)

In [19]:
d1=[[[4,6,7,8],
   [1,2,3,4],
   [7,8,9,0]]]
d1

[[[4, 6, 7, 8], [1, 2, 3, 4], [7, 8, 9, 0]]]

In [20]:
d1=np.array(d1)

In [23]:
d1.shape

(1, 3, 4)

In [24]:
type(d1)

numpy.ndarray

In [25]:
g=[4,8,6,7]
g

[4, 8, 6, 7]

In [26]:
g*3

[4, 8, 6, 7, 4, 8, 6, 7, 4, 8, 6, 7]

In [30]:
g1=[]
for i in g:
    g1.append(i*3)
    g1
    
    




In [31]:
g1

[12, 24, 18, 21]

In [32]:
type(g1)

list

In [39]:
a=[4,5,6,7]
a

[4, 5, 6, 7]

In [40]:
p = 1
for i in a:
    p = p*i

In [41]:
p

840

In [42]:
np.prod(a)

np.int64(840)

In [43]:
np.mean(a)

np.float64(5.5)

In [44]:
np.sum(a)

np.int64(22)

In [45]:
np.median(a)

np.float64(5.5)

In [46]:
np.std(a)

np.float64(1.118033988749895)

In [52]:
b = [[3, 4, 5, 6],
     [7, 8, 9, 10],
     [6,5,4,3]]

In [53]:
np.sum(b)

np.int64(70)

In [54]:
np.sum(b, axis=0)

array([16, 17, 18, 19])

In [57]:
np.sum(b, axis=1)

array([18, 34, 18])

In [60]:
range(1,5,10)

range(1, 5, 10)